# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paradiso}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Bergoo"]
  s.date = %q{2010-10-10}
  s.default_executable = %q{paradiso}
  s.description = %q{A simplified mplayer command line interface}
  s.email = %q{victor.bergoo@gmail.com}
  s.executables = ["paradiso"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/paradiso",
     "lib/paradiso.rb",
     "lib/paradiso/base.rb",
     "lib/paradiso/playlist.rb",
     "paradiso.gemspec"
  ]
  s.homepage = %q{http://github.com/netfeed/paradiso}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A command line interface for mplayer}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<popen4>, [">= 0"])
    else
      s.add_dependency(%q<popen4>, [">= 0"])
    end
  else
    s.add_dependency(%q<popen4>, [">= 0"])
  end
end

